// Generated by gencpp from file led_msgs/SetLEDRequest.msg
// DO NOT EDIT!


#ifndef LED_MSGS_MESSAGE_SETLEDREQUEST_H
#define LED_MSGS_MESSAGE_SETLEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace led_msgs
{
template <class ContainerAllocator>
struct SetLEDRequest_
{
  typedef SetLEDRequest_<ContainerAllocator> Type;

  SetLEDRequest_()
    : index(0)
    , r(0)
    , g(0)
    , b(0)  {
    }
  SetLEDRequest_(const ContainerAllocator& _alloc)
    : index(0)
    , r(0)
    , g(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef uint32_t _index_type;
  _index_type index;

   typedef uint8_t _r_type;
  _r_type r;

   typedef uint8_t _g_type;
  _g_type g;

   typedef uint8_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::led_msgs::SetLEDRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::led_msgs::SetLEDRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetLEDRequest_

typedef ::led_msgs::SetLEDRequest_<std::allocator<void> > SetLEDRequest;

typedef boost::shared_ptr< ::led_msgs::SetLEDRequest > SetLEDRequestPtr;
typedef boost::shared_ptr< ::led_msgs::SetLEDRequest const> SetLEDRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::led_msgs::SetLEDRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::led_msgs::SetLEDRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::led_msgs::SetLEDRequest_<ContainerAllocator1> & lhs, const ::led_msgs::SetLEDRequest_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.r == rhs.r &&
    lhs.g == rhs.g &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::led_msgs::SetLEDRequest_<ContainerAllocator1> & lhs, const ::led_msgs::SetLEDRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace led_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::led_msgs::SetLEDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::led_msgs::SetLEDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::led_msgs::SetLEDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::led_msgs::SetLEDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::led_msgs::SetLEDRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::led_msgs::SetLEDRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::led_msgs::SetLEDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8399dd204833059d357059fb17a8a497";
  }

  static const char* value(const ::led_msgs::SetLEDRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8399dd204833059dULL;
  static const uint64_t static_value2 = 0x357059fb17a8a497ULL;
};

template<class ContainerAllocator>
struct DataType< ::led_msgs::SetLEDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "led_msgs/SetLEDRequest";
  }

  static const char* value(const ::led_msgs::SetLEDRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::led_msgs::SetLEDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This service sets an LED color\n"
"\n"
"uint32 index   # number of LED in a LED strip or other LEDs set\n"
"uint8 r        # red component of the color, 0..255\n"
"uint8 g        # green component of the color, 0..255\n"
"uint8 b        # blue component of the color, 0..255\n"
;
  }

  static const char* value(const ::led_msgs::SetLEDRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::led_msgs::SetLEDRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.r);
      stream.next(m.g);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLEDRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::led_msgs::SetLEDRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::led_msgs::SetLEDRequest_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.index);
    s << indent << "r: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.r);
    s << indent << "g: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.g);
    s << indent << "b: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LED_MSGS_MESSAGE_SETLEDREQUEST_H
