// Generated by gencpp from file led_msgs/SetLEDs.msg
// DO NOT EDIT!


#ifndef LED_MSGS_MESSAGE_SETLEDS_H
#define LED_MSGS_MESSAGE_SETLEDS_H

#include <ros/service_traits.h>


#include <led_msgs/SetLEDsRequest.h>
#include <led_msgs/SetLEDsResponse.h>


namespace led_msgs
{

struct SetLEDs
{

typedef SetLEDsRequest Request;
typedef SetLEDsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLEDs
} // namespace led_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::led_msgs::SetLEDs > {
  static const char* value()
  {
    return "5d1b69ceca17a5820bdc2aeaae6d85b9";
  }

  static const char* value(const ::led_msgs::SetLEDs&) { return value(); }
};

template<>
struct DataType< ::led_msgs::SetLEDs > {
  static const char* value()
  {
    return "led_msgs/SetLEDs";
  }

  static const char* value(const ::led_msgs::SetLEDs&) { return value(); }
};


// service_traits::MD5Sum< ::led_msgs::SetLEDsRequest> should match
// service_traits::MD5Sum< ::led_msgs::SetLEDs >
template<>
struct MD5Sum< ::led_msgs::SetLEDsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::led_msgs::SetLEDs >::value();
  }
  static const char* value(const ::led_msgs::SetLEDsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::led_msgs::SetLEDsRequest> should match
// service_traits::DataType< ::led_msgs::SetLEDs >
template<>
struct DataType< ::led_msgs::SetLEDsRequest>
{
  static const char* value()
  {
    return DataType< ::led_msgs::SetLEDs >::value();
  }
  static const char* value(const ::led_msgs::SetLEDsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::led_msgs::SetLEDsResponse> should match
// service_traits::MD5Sum< ::led_msgs::SetLEDs >
template<>
struct MD5Sum< ::led_msgs::SetLEDsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::led_msgs::SetLEDs >::value();
  }
  static const char* value(const ::led_msgs::SetLEDsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::led_msgs::SetLEDsResponse> should match
// service_traits::DataType< ::led_msgs::SetLEDs >
template<>
struct DataType< ::led_msgs::SetLEDsResponse>
{
  static const char* value()
  {
    return DataType< ::led_msgs::SetLEDs >::value();
  }
  static const char* value(const ::led_msgs::SetLEDsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LED_MSGS_MESSAGE_SETLEDS_H
