// Generated by gencpp from file clover/Execute.msg
// DO NOT EDIT!


#ifndef CLOVER_MESSAGE_EXECUTE_H
#define CLOVER_MESSAGE_EXECUTE_H

#include <ros/service_traits.h>


#include <clover/ExecuteRequest.h>
#include <clover/ExecuteResponse.h>


namespace clover
{

struct Execute
{

typedef ExecuteRequest Request;
typedef ExecuteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Execute
} // namespace clover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clover::Execute > {
  static const char* value()
  {
    return "39a6fda3761b984206ead71aea9c2751";
  }

  static const char* value(const ::clover::Execute&) { return value(); }
};

template<>
struct DataType< ::clover::Execute > {
  static const char* value()
  {
    return "clover/Execute";
  }

  static const char* value(const ::clover::Execute&) { return value(); }
};


// service_traits::MD5Sum< ::clover::ExecuteRequest> should match
// service_traits::MD5Sum< ::clover::Execute >
template<>
struct MD5Sum< ::clover::ExecuteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clover::Execute >::value();
  }
  static const char* value(const ::clover::ExecuteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::ExecuteRequest> should match
// service_traits::DataType< ::clover::Execute >
template<>
struct DataType< ::clover::ExecuteRequest>
{
  static const char* value()
  {
    return DataType< ::clover::Execute >::value();
  }
  static const char* value(const ::clover::ExecuteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clover::ExecuteResponse> should match
// service_traits::MD5Sum< ::clover::Execute >
template<>
struct MD5Sum< ::clover::ExecuteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clover::Execute >::value();
  }
  static const char* value(const ::clover::ExecuteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::ExecuteResponse> should match
// service_traits::DataType< ::clover::Execute >
template<>
struct DataType< ::clover::ExecuteResponse>
{
  static const char* value()
  {
    return DataType< ::clover::Execute >::value();
  }
  static const char* value(const ::clover::ExecuteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLOVER_MESSAGE_EXECUTE_H
