// Generated by gencpp from file clover/GetTelemetryRequest.msg
// DO NOT EDIT!


#ifndef CLOVER_MESSAGE_GETTELEMETRYREQUEST_H
#define CLOVER_MESSAGE_GETTELEMETRYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clover
{
template <class ContainerAllocator>
struct GetTelemetryRequest_
{
  typedef GetTelemetryRequest_<ContainerAllocator> Type;

  GetTelemetryRequest_()
    : frame_id()  {
    }
  GetTelemetryRequest_(const ContainerAllocator& _alloc)
    : frame_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
  _frame_id_type frame_id;





  typedef boost::shared_ptr< ::clover::GetTelemetryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clover::GetTelemetryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetTelemetryRequest_

typedef ::clover::GetTelemetryRequest_<std::allocator<void> > GetTelemetryRequest;

typedef boost::shared_ptr< ::clover::GetTelemetryRequest > GetTelemetryRequestPtr;
typedef boost::shared_ptr< ::clover::GetTelemetryRequest const> GetTelemetryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clover::GetTelemetryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clover::GetTelemetryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clover::GetTelemetryRequest_<ContainerAllocator1> & lhs, const ::clover::GetTelemetryRequest_<ContainerAllocator2> & rhs)
{
  return lhs.frame_id == rhs.frame_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clover::GetTelemetryRequest_<ContainerAllocator1> & lhs, const ::clover::GetTelemetryRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clover::GetTelemetryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clover::GetTelemetryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clover::GetTelemetryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clover::GetTelemetryRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clover::GetTelemetryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clover::GetTelemetryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clover::GetTelemetryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "371cb926969bb965addb80f752c7ca31";
  }

  static const char* value(const ::clover::GetTelemetryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x371cb926969bb965ULL;
  static const uint64_t static_value2 = 0xaddb80f752c7ca31ULL;
};

template<class ContainerAllocator>
struct DataType< ::clover::GetTelemetryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clover/GetTelemetryRequest";
  }

  static const char* value(const ::clover::GetTelemetryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clover::GetTelemetryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string frame_id\n"
;
  }

  static const char* value(const ::clover::GetTelemetryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clover::GetTelemetryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTelemetryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clover::GetTelemetryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clover::GetTelemetryRequest_<ContainerAllocator>& v)
  {
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLOVER_MESSAGE_GETTELEMETRYREQUEST_H
