// Generated by gencpp from file clover/GetTelemetry.msg
// DO NOT EDIT!


#ifndef CLOVER_MESSAGE_GETTELEMETRY_H
#define CLOVER_MESSAGE_GETTELEMETRY_H

#include <ros/service_traits.h>


#include <clover/GetTelemetryRequest.h>
#include <clover/GetTelemetryResponse.h>


namespace clover
{

struct GetTelemetry
{

typedef GetTelemetryRequest Request;
typedef GetTelemetryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTelemetry
} // namespace clover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clover::GetTelemetry > {
  static const char* value()
  {
    return "3f1c3a9f95e1194fe8ebc671ce98ef91";
  }

  static const char* value(const ::clover::GetTelemetry&) { return value(); }
};

template<>
struct DataType< ::clover::GetTelemetry > {
  static const char* value()
  {
    return "clover/GetTelemetry";
  }

  static const char* value(const ::clover::GetTelemetry&) { return value(); }
};


// service_traits::MD5Sum< ::clover::GetTelemetryRequest> should match
// service_traits::MD5Sum< ::clover::GetTelemetry >
template<>
struct MD5Sum< ::clover::GetTelemetryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clover::GetTelemetry >::value();
  }
  static const char* value(const ::clover::GetTelemetryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::GetTelemetryRequest> should match
// service_traits::DataType< ::clover::GetTelemetry >
template<>
struct DataType< ::clover::GetTelemetryRequest>
{
  static const char* value()
  {
    return DataType< ::clover::GetTelemetry >::value();
  }
  static const char* value(const ::clover::GetTelemetryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clover::GetTelemetryResponse> should match
// service_traits::MD5Sum< ::clover::GetTelemetry >
template<>
struct MD5Sum< ::clover::GetTelemetryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clover::GetTelemetry >::value();
  }
  static const char* value(const ::clover::GetTelemetryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::GetTelemetryResponse> should match
// service_traits::DataType< ::clover::GetTelemetry >
template<>
struct DataType< ::clover::GetTelemetryResponse>
{
  static const char* value()
  {
    return DataType< ::clover::GetTelemetry >::value();
  }
  static const char* value(const ::clover::GetTelemetryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLOVER_MESSAGE_GETTELEMETRY_H
