// Generated by gencpp from file clover/Navigate.msg
// DO NOT EDIT!


#ifndef CLOVER_MESSAGE_NAVIGATE_H
#define CLOVER_MESSAGE_NAVIGATE_H

#include <ros/service_traits.h>


#include <clover/NavigateRequest.h>
#include <clover/NavigateResponse.h>


namespace clover
{

struct Navigate
{

typedef NavigateRequest Request;
typedef NavigateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Navigate
} // namespace clover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clover::Navigate > {
  static const char* value()
  {
    return "d27cf8a87020c28b3d14e06881a86c21";
  }

  static const char* value(const ::clover::Navigate&) { return value(); }
};

template<>
struct DataType< ::clover::Navigate > {
  static const char* value()
  {
    return "clover/Navigate";
  }

  static const char* value(const ::clover::Navigate&) { return value(); }
};


// service_traits::MD5Sum< ::clover::NavigateRequest> should match
// service_traits::MD5Sum< ::clover::Navigate >
template<>
struct MD5Sum< ::clover::NavigateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clover::Navigate >::value();
  }
  static const char* value(const ::clover::NavigateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::NavigateRequest> should match
// service_traits::DataType< ::clover::Navigate >
template<>
struct DataType< ::clover::NavigateRequest>
{
  static const char* value()
  {
    return DataType< ::clover::Navigate >::value();
  }
  static const char* value(const ::clover::NavigateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clover::NavigateResponse> should match
// service_traits::MD5Sum< ::clover::Navigate >
template<>
struct MD5Sum< ::clover::NavigateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clover::Navigate >::value();
  }
  static const char* value(const ::clover::NavigateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::NavigateResponse> should match
// service_traits::DataType< ::clover::Navigate >
template<>
struct DataType< ::clover::NavigateResponse>
{
  static const char* value()
  {
    return DataType< ::clover::Navigate >::value();
  }
  static const char* value(const ::clover::NavigateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLOVER_MESSAGE_NAVIGATE_H
