// Generated by gencpp from file clover/NavigateGlobal.msg
// DO NOT EDIT!


#ifndef CLOVER_MESSAGE_NAVIGATEGLOBAL_H
#define CLOVER_MESSAGE_NAVIGATEGLOBAL_H

#include <ros/service_traits.h>


#include <clover/NavigateGlobalRequest.h>
#include <clover/NavigateGlobalResponse.h>


namespace clover
{

struct NavigateGlobal
{

typedef NavigateGlobalRequest Request;
typedef NavigateGlobalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NavigateGlobal
} // namespace clover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clover::NavigateGlobal > {
  static const char* value()
  {
    return "fd9375a2b183ad5a1c80cf671893464b";
  }

  static const char* value(const ::clover::NavigateGlobal&) { return value(); }
};

template<>
struct DataType< ::clover::NavigateGlobal > {
  static const char* value()
  {
    return "clover/NavigateGlobal";
  }

  static const char* value(const ::clover::NavigateGlobal&) { return value(); }
};


// service_traits::MD5Sum< ::clover::NavigateGlobalRequest> should match
// service_traits::MD5Sum< ::clover::NavigateGlobal >
template<>
struct MD5Sum< ::clover::NavigateGlobalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clover::NavigateGlobal >::value();
  }
  static const char* value(const ::clover::NavigateGlobalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::NavigateGlobalRequest> should match
// service_traits::DataType< ::clover::NavigateGlobal >
template<>
struct DataType< ::clover::NavigateGlobalRequest>
{
  static const char* value()
  {
    return DataType< ::clover::NavigateGlobal >::value();
  }
  static const char* value(const ::clover::NavigateGlobalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clover::NavigateGlobalResponse> should match
// service_traits::MD5Sum< ::clover::NavigateGlobal >
template<>
struct MD5Sum< ::clover::NavigateGlobalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clover::NavigateGlobal >::value();
  }
  static const char* value(const ::clover::NavigateGlobalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::NavigateGlobalResponse> should match
// service_traits::DataType< ::clover::NavigateGlobal >
template<>
struct DataType< ::clover::NavigateGlobalResponse>
{
  static const char* value()
  {
    return DataType< ::clover::NavigateGlobal >::value();
  }
  static const char* value(const ::clover::NavigateGlobalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLOVER_MESSAGE_NAVIGATEGLOBAL_H
