// Generated by gencpp from file clover/SetAttitude.msg
// DO NOT EDIT!


#ifndef CLOVER_MESSAGE_SETATTITUDE_H
#define CLOVER_MESSAGE_SETATTITUDE_H

#include <ros/service_traits.h>


#include <clover/SetAttitudeRequest.h>
#include <clover/SetAttitudeResponse.h>


namespace clover
{

struct SetAttitude
{

typedef SetAttitudeRequest Request;
typedef SetAttitudeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAttitude
} // namespace clover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clover::SetAttitude > {
  static const char* value()
  {
    return "cc2080a08d58c004756f050a7b2dc084";
  }

  static const char* value(const ::clover::SetAttitude&) { return value(); }
};

template<>
struct DataType< ::clover::SetAttitude > {
  static const char* value()
  {
    return "clover/SetAttitude";
  }

  static const char* value(const ::clover::SetAttitude&) { return value(); }
};


// service_traits::MD5Sum< ::clover::SetAttitudeRequest> should match
// service_traits::MD5Sum< ::clover::SetAttitude >
template<>
struct MD5Sum< ::clover::SetAttitudeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clover::SetAttitude >::value();
  }
  static const char* value(const ::clover::SetAttitudeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::SetAttitudeRequest> should match
// service_traits::DataType< ::clover::SetAttitude >
template<>
struct DataType< ::clover::SetAttitudeRequest>
{
  static const char* value()
  {
    return DataType< ::clover::SetAttitude >::value();
  }
  static const char* value(const ::clover::SetAttitudeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clover::SetAttitudeResponse> should match
// service_traits::MD5Sum< ::clover::SetAttitude >
template<>
struct MD5Sum< ::clover::SetAttitudeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clover::SetAttitude >::value();
  }
  static const char* value(const ::clover::SetAttitudeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::SetAttitudeResponse> should match
// service_traits::DataType< ::clover::SetAttitude >
template<>
struct DataType< ::clover::SetAttitudeResponse>
{
  static const char* value()
  {
    return DataType< ::clover::SetAttitude >::value();
  }
  static const char* value(const ::clover::SetAttitudeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLOVER_MESSAGE_SETATTITUDE_H
