// Generated by gencpp from file clover/SetLEDEffect.msg
// DO NOT EDIT!


#ifndef CLOVER_MESSAGE_SETLEDEFFECT_H
#define CLOVER_MESSAGE_SETLEDEFFECT_H

#include <ros/service_traits.h>


#include <clover/SetLEDEffectRequest.h>
#include <clover/SetLEDEffectResponse.h>


namespace clover
{

struct SetLEDEffect
{

typedef SetLEDEffectRequest Request;
typedef SetLEDEffectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLEDEffect
} // namespace clover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clover::SetLEDEffect > {
  static const char* value()
  {
    return "044f75c927403b22bd59e8dbf871eabd";
  }

  static const char* value(const ::clover::SetLEDEffect&) { return value(); }
};

template<>
struct DataType< ::clover::SetLEDEffect > {
  static const char* value()
  {
    return "clover/SetLEDEffect";
  }

  static const char* value(const ::clover::SetLEDEffect&) { return value(); }
};


// service_traits::MD5Sum< ::clover::SetLEDEffectRequest> should match
// service_traits::MD5Sum< ::clover::SetLEDEffect >
template<>
struct MD5Sum< ::clover::SetLEDEffectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clover::SetLEDEffect >::value();
  }
  static const char* value(const ::clover::SetLEDEffectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::SetLEDEffectRequest> should match
// service_traits::DataType< ::clover::SetLEDEffect >
template<>
struct DataType< ::clover::SetLEDEffectRequest>
{
  static const char* value()
  {
    return DataType< ::clover::SetLEDEffect >::value();
  }
  static const char* value(const ::clover::SetLEDEffectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clover::SetLEDEffectResponse> should match
// service_traits::MD5Sum< ::clover::SetLEDEffect >
template<>
struct MD5Sum< ::clover::SetLEDEffectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clover::SetLEDEffect >::value();
  }
  static const char* value(const ::clover::SetLEDEffectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::SetLEDEffectResponse> should match
// service_traits::DataType< ::clover::SetLEDEffect >
template<>
struct DataType< ::clover::SetLEDEffectResponse>
{
  static const char* value()
  {
    return DataType< ::clover::SetLEDEffect >::value();
  }
  static const char* value(const ::clover::SetLEDEffectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLOVER_MESSAGE_SETLEDEFFECT_H
