// Generated by gencpp from file clover/SetPosition.msg
// DO NOT EDIT!


#ifndef CLOVER_MESSAGE_SETPOSITION_H
#define CLOVER_MESSAGE_SETPOSITION_H

#include <ros/service_traits.h>


#include <clover/SetPositionRequest.h>
#include <clover/SetPositionResponse.h>


namespace clover
{

struct SetPosition
{

typedef SetPositionRequest Request;
typedef SetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPosition
} // namespace clover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clover::SetPosition > {
  static const char* value()
  {
    return "69cb8e201b1f4163f507e2b13fa97684";
  }

  static const char* value(const ::clover::SetPosition&) { return value(); }
};

template<>
struct DataType< ::clover::SetPosition > {
  static const char* value()
  {
    return "clover/SetPosition";
  }

  static const char* value(const ::clover::SetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::clover::SetPositionRequest> should match
// service_traits::MD5Sum< ::clover::SetPosition >
template<>
struct MD5Sum< ::clover::SetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clover::SetPosition >::value();
  }
  static const char* value(const ::clover::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::SetPositionRequest> should match
// service_traits::DataType< ::clover::SetPosition >
template<>
struct DataType< ::clover::SetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::clover::SetPosition >::value();
  }
  static const char* value(const ::clover::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clover::SetPositionResponse> should match
// service_traits::MD5Sum< ::clover::SetPosition >
template<>
struct MD5Sum< ::clover::SetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clover::SetPosition >::value();
  }
  static const char* value(const ::clover::SetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::SetPositionResponse> should match
// service_traits::DataType< ::clover::SetPosition >
template<>
struct DataType< ::clover::SetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::clover::SetPosition >::value();
  }
  static const char* value(const ::clover::SetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLOVER_MESSAGE_SETPOSITION_H
