// Generated by gencpp from file clover/SetVelocity.msg
// DO NOT EDIT!


#ifndef CLOVER_MESSAGE_SETVELOCITY_H
#define CLOVER_MESSAGE_SETVELOCITY_H

#include <ros/service_traits.h>


#include <clover/SetVelocityRequest.h>
#include <clover/SetVelocityResponse.h>


namespace clover
{

struct SetVelocity
{

typedef SetVelocityRequest Request;
typedef SetVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetVelocity
} // namespace clover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clover::SetVelocity > {
  static const char* value()
  {
    return "0c536fc3fdea57936646d4924e14c3d1";
  }

  static const char* value(const ::clover::SetVelocity&) { return value(); }
};

template<>
struct DataType< ::clover::SetVelocity > {
  static const char* value()
  {
    return "clover/SetVelocity";
  }

  static const char* value(const ::clover::SetVelocity&) { return value(); }
};


// service_traits::MD5Sum< ::clover::SetVelocityRequest> should match
// service_traits::MD5Sum< ::clover::SetVelocity >
template<>
struct MD5Sum< ::clover::SetVelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clover::SetVelocity >::value();
  }
  static const char* value(const ::clover::SetVelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::SetVelocityRequest> should match
// service_traits::DataType< ::clover::SetVelocity >
template<>
struct DataType< ::clover::SetVelocityRequest>
{
  static const char* value()
  {
    return DataType< ::clover::SetVelocity >::value();
  }
  static const char* value(const ::clover::SetVelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clover::SetVelocityResponse> should match
// service_traits::MD5Sum< ::clover::SetVelocity >
template<>
struct MD5Sum< ::clover::SetVelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clover::SetVelocity >::value();
  }
  static const char* value(const ::clover::SetVelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::SetVelocityResponse> should match
// service_traits::DataType< ::clover::SetVelocity >
template<>
struct DataType< ::clover::SetVelocityResponse>
{
  static const char* value()
  {
    return DataType< ::clover::SetVelocity >::value();
  }
  static const char* value(const ::clover::SetVelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLOVER_MESSAGE_SETVELOCITY_H
