// Generated by gencpp from file clover_blocks/LoadRequest.msg
// DO NOT EDIT!


#ifndef CLOVER_BLOCKS_MESSAGE_LOADREQUEST_H
#define CLOVER_BLOCKS_MESSAGE_LOADREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clover_blocks
{
template <class ContainerAllocator>
struct LoadRequest_
{
  typedef LoadRequest_<ContainerAllocator> Type;

  LoadRequest_()
    {
    }
  LoadRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::clover_blocks::LoadRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clover_blocks::LoadRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LoadRequest_

typedef ::clover_blocks::LoadRequest_<std::allocator<void> > LoadRequest;

typedef boost::shared_ptr< ::clover_blocks::LoadRequest > LoadRequestPtr;
typedef boost::shared_ptr< ::clover_blocks::LoadRequest const> LoadRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clover_blocks::LoadRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clover_blocks::LoadRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace clover_blocks

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clover_blocks::LoadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clover_blocks::LoadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clover_blocks::LoadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clover_blocks::LoadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clover_blocks::LoadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clover_blocks::LoadRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clover_blocks::LoadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::clover_blocks::LoadRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::clover_blocks::LoadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clover_blocks/LoadRequest";
  }

  static const char* value(const ::clover_blocks::LoadRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clover_blocks::LoadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::clover_blocks::LoadRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clover_blocks::LoadRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clover_blocks::LoadRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::clover_blocks::LoadRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CLOVER_BLOCKS_MESSAGE_LOADREQUEST_H
