// Generated by gencpp from file clover_blocks/Prompt.msg
// DO NOT EDIT!


#ifndef CLOVER_BLOCKS_MESSAGE_PROMPT_H
#define CLOVER_BLOCKS_MESSAGE_PROMPT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clover_blocks
{
template <class ContainerAllocator>
struct Prompt_
{
  typedef Prompt_<ContainerAllocator> Type;

  Prompt_()
    : message()
    , id()  {
    }
  Prompt_(const ContainerAllocator& _alloc)
    : message(_alloc)
    , id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::clover_blocks::Prompt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clover_blocks::Prompt_<ContainerAllocator> const> ConstPtr;

}; // struct Prompt_

typedef ::clover_blocks::Prompt_<std::allocator<void> > Prompt;

typedef boost::shared_ptr< ::clover_blocks::Prompt > PromptPtr;
typedef boost::shared_ptr< ::clover_blocks::Prompt const> PromptConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clover_blocks::Prompt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clover_blocks::Prompt_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clover_blocks::Prompt_<ContainerAllocator1> & lhs, const ::clover_blocks::Prompt_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clover_blocks::Prompt_<ContainerAllocator1> & lhs, const ::clover_blocks::Prompt_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clover_blocks

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clover_blocks::Prompt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clover_blocks::Prompt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clover_blocks::Prompt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clover_blocks::Prompt_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clover_blocks::Prompt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clover_blocks::Prompt_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clover_blocks::Prompt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d802ea50c4ef8e8ec9e793bc71e2160a";
  }

  static const char* value(const ::clover_blocks::Prompt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd802ea50c4ef8e8eULL;
  static const uint64_t static_value2 = 0xc9e793bc71e2160aULL;
};

template<class ContainerAllocator>
struct DataType< ::clover_blocks::Prompt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clover_blocks/Prompt";
  }

  static const char* value(const ::clover_blocks::Prompt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clover_blocks::Prompt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message  # message for prompt\n"
"string id  # user response should be published to ~input/<id> topic\n"
;
  }

  static const char* value(const ::clover_blocks::Prompt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clover_blocks::Prompt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Prompt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clover_blocks::Prompt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clover_blocks::Prompt_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLOVER_BLOCKS_MESSAGE_PROMPT_H
