// Generated by gencpp from file clover_blocks/Run.msg
// DO NOT EDIT!


#ifndef CLOVER_BLOCKS_MESSAGE_RUN_H
#define CLOVER_BLOCKS_MESSAGE_RUN_H

#include <ros/service_traits.h>


#include <clover_blocks/RunRequest.h>
#include <clover_blocks/RunResponse.h>


namespace clover_blocks
{

struct Run
{

typedef RunRequest Request;
typedef RunResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Run
} // namespace clover_blocks


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clover_blocks::Run > {
  static const char* value()
  {
    return "c0a76d801e7d5147feb773127182d76c";
  }

  static const char* value(const ::clover_blocks::Run&) { return value(); }
};

template<>
struct DataType< ::clover_blocks::Run > {
  static const char* value()
  {
    return "clover_blocks/Run";
  }

  static const char* value(const ::clover_blocks::Run&) { return value(); }
};


// service_traits::MD5Sum< ::clover_blocks::RunRequest> should match
// service_traits::MD5Sum< ::clover_blocks::Run >
template<>
struct MD5Sum< ::clover_blocks::RunRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clover_blocks::Run >::value();
  }
  static const char* value(const ::clover_blocks::RunRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover_blocks::RunRequest> should match
// service_traits::DataType< ::clover_blocks::Run >
template<>
struct DataType< ::clover_blocks::RunRequest>
{
  static const char* value()
  {
    return DataType< ::clover_blocks::Run >::value();
  }
  static const char* value(const ::clover_blocks::RunRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clover_blocks::RunResponse> should match
// service_traits::MD5Sum< ::clover_blocks::Run >
template<>
struct MD5Sum< ::clover_blocks::RunResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clover_blocks::Run >::value();
  }
  static const char* value(const ::clover_blocks::RunResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover_blocks::RunResponse> should match
// service_traits::DataType< ::clover_blocks::Run >
template<>
struct DataType< ::clover_blocks::RunResponse>
{
  static const char* value()
  {
    return DataType< ::clover_blocks::Run >::value();
  }
  static const char* value(const ::clover_blocks::RunResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLOVER_BLOCKS_MESSAGE_RUN_H
