// Generated by gencpp from file clover_blocks/Store.msg
// DO NOT EDIT!


#ifndef CLOVER_BLOCKS_MESSAGE_STORE_H
#define CLOVER_BLOCKS_MESSAGE_STORE_H

#include <ros/service_traits.h>


#include <clover_blocks/StoreRequest.h>
#include <clover_blocks/StoreResponse.h>


namespace clover_blocks
{

struct Store
{

typedef StoreRequest Request;
typedef StoreResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Store
} // namespace clover_blocks


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clover_blocks::Store > {
  static const char* value()
  {
    return "9e64eeb2e84c0420f3367c9e49c7fa5e";
  }

  static const char* value(const ::clover_blocks::Store&) { return value(); }
};

template<>
struct DataType< ::clover_blocks::Store > {
  static const char* value()
  {
    return "clover_blocks/Store";
  }

  static const char* value(const ::clover_blocks::Store&) { return value(); }
};


// service_traits::MD5Sum< ::clover_blocks::StoreRequest> should match
// service_traits::MD5Sum< ::clover_blocks::Store >
template<>
struct MD5Sum< ::clover_blocks::StoreRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clover_blocks::Store >::value();
  }
  static const char* value(const ::clover_blocks::StoreRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover_blocks::StoreRequest> should match
// service_traits::DataType< ::clover_blocks::Store >
template<>
struct DataType< ::clover_blocks::StoreRequest>
{
  static const char* value()
  {
    return DataType< ::clover_blocks::Store >::value();
  }
  static const char* value(const ::clover_blocks::StoreRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clover_blocks::StoreResponse> should match
// service_traits::MD5Sum< ::clover_blocks::Store >
template<>
struct MD5Sum< ::clover_blocks::StoreResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clover_blocks::Store >::value();
  }
  static const char* value(const ::clover_blocks::StoreResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover_blocks::StoreResponse> should match
// service_traits::DataType< ::clover_blocks::Store >
template<>
struct DataType< ::clover_blocks::StoreResponse>
{
  static const char* value()
  {
    return DataType< ::clover_blocks::Store >::value();
  }
  static const char* value(const ::clover_blocks::StoreResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLOVER_BLOCKS_MESSAGE_STORE_H
