// Generated by gencpp from file clover_blocks/StoreRequest.msg
// DO NOT EDIT!


#ifndef CLOVER_BLOCKS_MESSAGE_STOREREQUEST_H
#define CLOVER_BLOCKS_MESSAGE_STOREREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clover_blocks
{
template <class ContainerAllocator>
struct StoreRequest_
{
  typedef StoreRequest_<ContainerAllocator> Type;

  StoreRequest_()
    : name()
    , program()  {
    }
  StoreRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , program(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _program_type;
  _program_type program;





  typedef boost::shared_ptr< ::clover_blocks::StoreRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clover_blocks::StoreRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StoreRequest_

typedef ::clover_blocks::StoreRequest_<std::allocator<void> > StoreRequest;

typedef boost::shared_ptr< ::clover_blocks::StoreRequest > StoreRequestPtr;
typedef boost::shared_ptr< ::clover_blocks::StoreRequest const> StoreRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clover_blocks::StoreRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clover_blocks::StoreRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clover_blocks::StoreRequest_<ContainerAllocator1> & lhs, const ::clover_blocks::StoreRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.program == rhs.program;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clover_blocks::StoreRequest_<ContainerAllocator1> & lhs, const ::clover_blocks::StoreRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clover_blocks

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clover_blocks::StoreRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clover_blocks::StoreRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clover_blocks::StoreRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clover_blocks::StoreRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clover_blocks::StoreRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clover_blocks::StoreRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clover_blocks::StoreRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "172a974fe3707dd1b4918ae4f6e48e44";
  }

  static const char* value(const ::clover_blocks::StoreRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x172a974fe3707dd1ULL;
  static const uint64_t static_value2 = 0xb4918ae4f6e48e44ULL;
};

template<class ContainerAllocator>
struct DataType< ::clover_blocks::StoreRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clover_blocks/StoreRequest";
  }

  static const char* value(const ::clover_blocks::StoreRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clover_blocks::StoreRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string program\n"
;
  }

  static const char* value(const ::clover_blocks::StoreRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clover_blocks::StoreRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.program);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StoreRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clover_blocks::StoreRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clover_blocks::StoreRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "program: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.program);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLOVER_BLOCKS_MESSAGE_STOREREQUEST_H
